

## clean all modules
clean:
	mvn -amd  clean

## clean and install the modules
build:
	mvn -amd clean install

## build but skip tests
backend-build:
	mvn -amd clean install -Dmaven.test.skip -DskipTests

