Makefile

## clean module
clean:
	mvn -amd  clean

## clean and install module
build:
	mvn -amd clean install

## clean and install module but skip tests
backend-build:
	mvn -amd clean install -Dmaven.test.skip -DskipTests

